# Берём минимальный образ Node.js
FROM node:20-alpine

RUN apk add --no-cache curl

# Устанавливаем pnpm глобально
RUN npm install -g pnpm

# Рабочая директория внутри контейнера
WORKDIR /app

# Копируем файлы с зависимостями
COPY package*.json ./
RUN pnpm install

# Копируем весь проект
COPY . .

# Команда запуска сервера
EXPOSE 3000
CMD ["node", "server.js"]
