name: Build and push Docker images

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: tickertape/homelab-frontend:latest

      # Build server
      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: tickertape/homelab-server:latest

      # Build nginx (если нужен кастомный образ — добавь Dockerfile)
      # Если нет, этот шаг можно убрать и использовать просто nginx:alpine
      # - name: Build and push nginx
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./nginx
      #     file: ./nginx/Dockerfile
      #     push: true
      #     tags: tickertape/homelab-nginx:latest
